%% Diagrama de Casos de Uso para as Histórias de Usuário
actor Funcionario

usecase "Cadastrar Placa de Veículo" as UC1
usecase "Consultar Placas Cadastradas" as UC2
usecase "Consultar Vagas Disponíveis" as UC3
usecase "Consultar Tempo de Permanência e Saldo" as UC4
usecase "Consultar Planos de Fidelidade" as UC5

Funcionario --> UC1
Funcionario --> UC2
Funcionario --> UC3
Funcionario --> UC4
Funcionario --> UC5
